<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\ReceiveStorageController.cs" />
    <Compile Remove="Model\ReceiveStorageDto.cs" />
  </ItemGroup>

  <ItemGroup>
    
    <PackageReference Include="Dapper" Version="2.1.66" />
    
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.6.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
    
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Uploads\UserProfile\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Controllers\ReceiveStorageController.cs" />
    <None Include="Model\ReceiveStorageDto.cs" />
  </ItemGroup>

</Project>
