namespace UPSWCAPI.Model
{
    public class PayRegister
    {
        public int EmpId { get; set; }
        public int PayYear { get; set; }
        public int PayMonth { get; set; }
        public decimal WorkDays { get; set; }
        public decimal SusDays { get; set; }
        public decimal SusPer { get; set; }
        public int GradePayId { get; set; }
        public int CircleId { get; set; }
        public decimal BasicSal { get; set; }
        public decimal GradePay { get; set; }
        public decimal DAPer { get; set; }
        public decimal DA { get; set; }
        public decimal MA { get; set; }
        public decimal WA { get; set; }
        public decimal IR { get; set; }
        public decimal CCA { get; set; }
        public decimal HRA { get; set; }
        public decimal PerPay { get; set; }
        public decimal SpecPay { get; set; }
        public decimal PenContribution { get; set; }
        public decimal PPFContribution { get; set; }
        public decimal BilangAllow { get; set; }
        public decimal NPSEmployer { get; set; }
        public decimal NPSEmployee { get; set; }
        public decimal DisAllow { get; set; }
        public decimal DepAllow { get; set; }
        public decimal VehicleAllow { get; set; }
        public decimal OtherAllow { get; set; }
        public decimal MiscAllowAmt1 { get; set; }
        public string MiscAllowDesc1 { get; set; }
        public decimal MiscAllowAmt2 { get; set; }
        public string MiscAllowDesc2 { get; set; }
        public decimal MiscAllowAmt3 { get; set; }
        public string MiscAllowDesc3 { get; set; }
        public decimal MiscAllowAmt4 { get; set; }
        public string MiscAllowDesc4 { get; set; }
        public decimal MiscDedAmt1 { get; set; }
        public string MiscDedDesc1 { get; set; }
        public decimal MiscDedAmt2 { get; set; }
        public string MiscDedDesc2 { get; set; }
        public decimal MiscDedAmt3 { get; set; }
        public string MiscDedDesc3 { get; set; }
        public decimal MiscDedAmt4 { get; set; }
        public string MiscDedDesc4 { get; set; }
        public decimal GrossPay { get; set; }
        public int GPFTypeId { get; set; }
        public decimal GPF { get; set; }
        public decimal PPF { get; set; }
        public decimal LIC { get; set; }
        public decimal GIS { get; set; }
        public decimal VehicleCharges { get; set; }
        public decimal IncomeTax { get; set; }
        public decimal CourtReco { get; set; }
        public decimal QtrRent { get; set; }
        public decimal Society { get; set; }
        public decimal GPFAdv { get; set; }
        public decimal CPFAdv { get; set; }
        public decimal SCCar { get; set; }
        public decimal SCCarInt { get; set; }
        public decimal BidAdv { get; set; }
        public decimal BidInt { get; set; }
        public decimal HDFC { get; set; }
        public decimal NameAC { get; set; }
        public decimal FestivalAdv { get; set; }
        public decimal Genloan { get; set; }
        public decimal GenLoanInt { get; set; }
        public decimal CALoan { get; set; }
        public decimal CALoanInt { get; set; }
        public decimal MiscReco { get; set; }
        public decimal OtherReco { get; set; }
        public decimal StaffAdv { get; set; }
        public decimal CoOperative { get; set; }
        public decimal Penalty { get; set; }
        public decimal Rd { get; set; }
        public decimal NetPay { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public DateTime entrydate { get; set; }
        public string salarytype { get; set; }
        public int UserId { get; set; }
        public int OfficeId { get; set; }
        public int DepartmentId { get; set; }
        public int SubDeptId { get; set; }
        public int DesigId { get; set; }
        public int CommssionId { get; set; }
        public int LevelId { get; set; }
        public int IncrementId { get; set; }
        public string IPAddress { get; set; }
        public decimal BasicPay { get; set; }
        public string AccountNo { get; set; }
        public int BranchId { get; set; }
        public string GPFCode { get; set; }
        public string CPFCode { get; set; }
        public string PFMSCode { get; set; }
        public int ScaleId { get; set; }
        public int HeadId { get; set; }
        public DateTime UpdateDate { get; set; }
        public string E_HRMSId { get; set; }
    }
}
